server.shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 10s
spring.main.allow-bean-definition-overriding: true

app:
  eureka-username: dev-usr
  eureka-password: dev-pwd

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

spring.redis:
  host: localhost
  port: 6379
  timeout: 3000
  password: dev-pwd

spring.rabbitmq:
  host: localhost
  port: 5672
  username: dev-usr
  password: dev-pwd
management.health.rabbit.enabled: true

feign:
  client:
    config:
      default:
        loggerLevel: HEADERS
        connectTimeout: 5000
        readTimeout: 5000
  httpclient:
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
    ok-http:
      read-timeout: 5s
  okhttp:
    enabled: true
    loadbalancer:
      enabled: true
  circuitbreaker:
    enabled: true

spring.zipkin.base-url: http://localhost:9411/
spring.cloud.sleuth:
  sampler.probability: 1

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
management.info.git.enabled: true
management.info.git.mode: full
management.endpoint.health.probes.enabled: true


---
spring.config.activate.on-profile: docker

eureka.client.serviceUrl.defaultZone: http://${app.eureka-username}:${app.eureka-password}@eureka-server:8761/eureka/

spring.redis.host: redis

spring.rabbitmq.host: rabbitmq

spring.zipkin.base-url: http://zipkin:9411/
