spring:
  application:
    name: chensoul-examples-audit

chensoul.audit.engine.enabled: true
chensoul.audit.slf4j.enabled: true

security:
  oauth2:
    client:
      ignore-urls:
        - /actuator/**
        - /v3/api-docs
        - /swagger-ui/**
        - /resources/**
    resource:
      jwk:
        key-set-uri: http://localhost:6006/jwks
