# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-maven-plugin
        versions:
          - ">= 3"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Shanghai"
