version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=chensoul-cloud
      - MYSQL_USER=dev-usr
      - MYSQL_PASSWORD=dev-pwd
    healthcheck:
      test: "/usr/bin/mysql --user=dev-usr --password=dev-pwd -e 'SHOW DATABASES;'"
      interval: 5s
      timeout: 2s
      retries: 10

  #  mysql-master:
  #    image: mysql:8.3.0
  #    ports:
  #      - "3307:3306"
  #    environment:
  #        - TZ=Asia/Shanghai
  #        - MYSQL_ROOT_PASSWORD=rootpwd
  #        - MYSQL_DATABASE=chensoul-cloud
  #        - MYSQL_USER=dev-usr
  #        - MYSQL_PASSWORD=dev-pwd
  #    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=true --lower_case_table_names=1 --tls-version='' --log-bin=mysql-bin --server-id=1
  #    healthcheck:
  #      test: "/usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} -e 'SHOW DATABASES;'"
  #      interval: 5s
  #      timeout: 2s
  #      retries: 10
  #
  #  mysql-slave:
  #    image: mysql:8.3.0
  #    ports:
  #      - "3308:3306"
  #    environment:
  #        - TZ=Asia/Shanghai
  #        - MYSQL_ROOT_PASSWORD=rootpwd
  #        - MYSQL_DATABASE=chensoul-cloud
  #        - MYSQL_USER=dev-usr
  #        - MYSQL_PASSWORD=dev-pwd
  #    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=true --lower_case_table_names=1 --tls-version='' --log-bin=mysql-bin --server-id=2
  #    healthcheck:
  #      test: "/usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} -e 'SHOW DATABASES;'"
  #      interval: 5s
  #      timeout: 2s
  #      retries: 10

  redis:
    image: redis:7.2.4
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "6379:6379"
    command: redis-server --requirepass dev-pwd
    healthcheck:
      test: [ "CMD", "redis-cli","-a","dev-pwd","--raw", "incr","ping" ]
      interval: 5s
      timeout: 2s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13.0-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 2s
      retries: 10

  zipkin:
    image: openzipkin/zipkin:3.1.1
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "9411:9411"

  #
  #  kafka:
  #    image: confluentinc/cp-kafka:7.6.0
  #    ports:
  #      - "9092:9092"
  #    environment:
  #      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  #      - KAFKA_BROKER_ID=1
  #      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  #    depends_on:
  #      - zookeeper
  #
  #  zookeeper:
  #    image: confluentinc/cp-zookeeper:7.6.0
  #    restart: always
  #    ports:
  #      - "2181:2181"
  #    environment:
  #      - ZOOKEEPER_CLIENT_PORT=2181
  #
  #  nacos:
  #    build: spring-cloud/nacos
  #    ports:
  #      - "8848:8848"
  #      - "9848:9848"
  #      - "9849:9849"
  #
  #  sentinel:
  #    build: spring-cloud/sentinel
  #    ports:
  #      - "5300:5300"

  #  xxl-job:
  #    build: spring-cloud/xxl-job
  #    environment:
  #      - TZ=Asia/Shanghai
  #    ports:
  #      - "5200:5200"
  #

  config-server:
    build: spring-cloud/config-server
    image: chensoul/config-server
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker,native
      - ENCRYPT_KEY=${CONFIG_SERVER_ENCRYPT_KEY}
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD}
    volumes:
      - ./config-repo:/config-repo

  eureka-server:
    build: spring-cloud/eureka-server
    image: chensoul/eureka-server
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    ports:
      - "8761:8761"

  gateway:
    build: spring-cloud/gateway
    image: chensoul/gateway
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    ports:
      - "8443:8443"

  monitor-server:
    build: spring-cloud/monitor-server
    image: chensoul/monitor-server
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}

  auth-server:
    build: spring-cloud/auth-server
    image: chensoul/auth-server
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    healthcheck:
      test: [ "CMD", "curl", "-fs", "http://localhost:8080/actuator/health" ]
      interval: 5s
      timeout: 2s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
