server.port: 8888

spring:
  application.name: @artifactId@
  profiles.active: native

spring.cloud.config.server.native.searchLocations: file:${PWD:}/config-repo

encrypt.key: ${CONFIG_SERVER_ENCRYPT_KEY:my-very-secure-encrypt-key}
spring.security.user.name: ${CONFIG_SERVER_USER_NAME:user}
spring.security.user.password: ${CONFIG_SERVER_USER_PASSWORD:devpwd}

management.endpoint.health.show-details: ALWAYS
management.endpoints.web.exposure.include: "*"
