spring.application.name: @artifactId@

spring.config.import: "optional:configserver:"

spring:
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 10
    uri: http://${config-server:config-server}:8888
    username: ${CONFIG_SERVER_USR:dev-usr}
    password: ${CONFIG_SERVER_PWD:dev-pwd}


