spring.application.name: @artifactId@


spring.config.import:
  - "optional:configserver:"

spring:
  cloud.config:
    failFast: false
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 10
    uri: http://localhost:8888
    username: ${CONFIG_SERVER_USR:dev-usr}
    password: ${CONFIG_SERVER_PWD:dev-pwd}


---
spring.config.activate.on-profile: docker

spring.cloud.config.uri: http://config-server:8888
