version: '3.0'

services:
  postgres:
    restart: always
    image: postgres:15
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: chensoul
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data: { }
