spring.config.import: "optional:configserver:"

spring.application.name: @artifactId@

spring:
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 10
    uri: http://${config-server:config-server}:8888
    username: ${CONFIG_SERVER_USR:dev-usr}
    password: ${CONFIG_SERVER_PWD:dev-pwd}


logging.level:
  org.apache.coyote.http11.Http11InputBuffer: DEBUG
  org.springframework.cloud.config.client: DEBUG
