# https://github.com/mojohaus/flatten-maven-plugin/blob/master/.github/workflows/release-drafter.yml

name: Release Drafter
on:
  push:
    branches:
      - main
jobs:
  update_release_draft:
    uses: apache/maven-gh-actions-shared/.github/workflows/release-drafter.yml@v4
